# Generated by Django 5.2.1 on 2025-06-12 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_staff'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='staff',
            table='staff',
        ),
    ]
