# Generated by Django 5.2.1 on 2025-05-27 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('coupon_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('coupon_code', models.CharField(max_length=32, unique=True)),
                ('expiry_date', models.DateField()),
                ('discount_percentage', models.FloatField()),
                ('max_usage', models.IntegerField(default=2)),
            ],
        ),
    ]
